version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "sa"
    ports:
      - "15432:5432"
    volumes:
      - ../database:/var/lib/postgresql/data 
  
  boaideia-backend:
    build: ../boaideia-backend/
    ports:
      - "80:80"
    depends_on:
      - "db"