version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "sa"
    ports:
      - "15432:5432"
    volumes:
      - ../database:/var/lib/postgresql/data 
  
  boaideia-backend:
    build: ../boaideia-backend/
    depends_on:
      - "db"

  boaideia-frontend:
    build: ../boaideia-frontend/
    depends_on: 
      - boaideia-backend
    ports: 
      - 3000:3000
  
  nginx:
    build: ./nginx
    ports:
      - 80:80
