version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "sa"
    ports:
      - "15432:5432"
    volumes:
      - ../database:/var/lib/postgresql/data 
  
  backend:
    build: ../boaideia-backend/
    depends_on:
      - "db"

  frontend:
    build: ../boaideia-frontend/
    depends_on: 
      - backend
    ports: 
      - 3000:3000
  
  nginx:
    build: ./nginx
    depends_on: 
      - backend
      - frontend
    ports:
      - 80:80
